apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: voteservicelb
spec:
  type: LoadBalancer 
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: vote
  
